version: '3.8'
services:
  web:
    build: ./client
    env_file:
      - ./client/.env
    ports:
      - 3000:3000
  api:
    build: ./server
    env_file:
      - ./client/.env
    ports:
      - 5000:5000
volumes:
  irs:
